

[north_nfoi_a,north_nfoi_c]=comps_trapped(['/Volumes/matlab/matlab/north/' ...
                    'north_tracks_32_weeks.mat'],'nfoi_sample');
[north_nssh_a,north_nssh_c]=comps_trapped(['/Volumes/matlab/matlab/north/' ...
                    'north_tracks_32_weeks.mat'],'nssh_sample');

[south_nfoi_a,south_nfoi_c]=comps_trapped(['/Volumes/matlab/matlab/south/' ...
                    'south_tracks_32_weeks.mat'],'nfoi_sample');
[south_nssh_a,south_nssh_c]=comps(['/Volumes/matlab/matlab/south/' ...
                    'south_tracks_32_weeks.mat'],'nssh_sample');
