clear all
rgrid_grid
[r,c]=imap(-3,3,-3,3,yi,xi);


	

[LW_achl_a,LW_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/pos_chl_anom_tracks.mat',...
				'nrhp21_chl_sample','n');
				
[LW_wek_a,LW_wek_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/pos_chl_anom_tracks.mat',...
				'nrw_ek_sample','n');				


%{	
[LW_achl_a,LW_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/cLW_lat_lon_tracks.mat',...
				'nrhp21_chl_sample','n');
				
[LW_wek_a,LW_wek_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/cLW_lat_lon_tracks.mat',...
				'nrw_ek_sample','n');	


[oID_achl_a,oID_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oID_lat_lon_tracks.mat',...
				'nrgchl_anom_sample','n');
[oNPC_achl_a,oNPC_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNPC_lat_lon_tracks.mat',...
				'nrgchl_anom_sample','n');
[oSPC_achl_a,oSPC_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSPC_lat_lon_tracks.mat',...
				'nrgchl_anom_sample','n');
[oNAT_achl_a,oNAT_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNAT_lat_lon_tracks.mat',...
				'nrgchl_anom_sample','n');
[oSAT_achl_a,oSAT_achl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSAT_lat_lon_tracks.mat',...
				'nrgchl_anom_sample','n');	
			
				[oID_foi_a,oID_foi_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oID_lat_lon_tracks.mat',...
				'nrfiltered_sst_oi_sample','n');
[oNPC_foi_a,oNPC_foi_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNPC_lat_lon_tracks.mat',...
				'nrfiltered_sst_oi_sample','n');
[oSPC_foi_a,oSPC_foi_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSPC_lat_lon_tracks.mat',...
				'nrfiltered_sst_oi_sample','n');
[oNAT_foi_a,oNAT_foi_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNAT_lat_lon_tracks.mat',...
				'nrfiltered_sst_oi_sample','n');
[oSAT_foi_a,oSAT_foi_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSAT_lat_lon_tracks.mat',...
				'nrfiltered_sst_oi_sample','n');	
				

[oID_spd_a,oID_spd_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oID_lat_lon_tracks.mat',...
				'nrhp_wspd_sample','n');
[oNPC_spd_a,oNPC_spd_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNPC_lat_lon_tracks.mat',...
				'nrhp_wspd_sample','n');
[oSPC_spd_a,oSPC_spd_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSPC_lat_lon_tracks.mat',...
				'nrhp_wspd_sample','n');
[oNAT_spd_a,oNAT_spd_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNAT_lat_lon_tracks.mat',...
				'nrhp_wspd_sample','n');
[oSAT_spd_a,oSAT_spd_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSAT_lat_lon_tracks.mat',...
				'nrhp_wspd_sample','n');
	
	
[oID_crl_a,oID_crl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oID_lat_lon_tracks.mat',...
				'nrhp66_crl_sample','n');
[oNPC_crl_a,oNPC_crl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNPC_lat_lon_tracks.mat',...
				'nrhp66_crl_sample','n');
[oSPC_crl_a,oSPC_crl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSPC_lat_lon_tracks.mat',...
				'nrhp66_crl_sample','n');
[oNAT_crl_a,oNAT_crl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNAT_lat_lon_tracks.mat',...
				'nrhp66_crl_sample','n');
[oSAT_crl_a,oSAT_crl_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSAT_lat_lon_tracks.mat',...
				'nrhp66_crl_sample','n');				
				

[oID_crlg_a,oID_crlg_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oID_lat_lon_tracks.mat',...
				'nrhp66_crlg_sample','n');
[oNPC_crlg_a,oNPC_crlg_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNPC_lat_lon_tracks.mat',...
				'nrhp66_crlg_sample','n');
[oSPC_crlg_a,oSPC_crlg_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSPC_lat_lon_tracks.mat',...
				'nrhp66_crlg_sample','n');
[oNAT_crlg_a,oNAT_crlg_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oNAT_lat_lon_tracks.mat',...
				'nrhp66_crlg_sample','n');
[oSAT_crlg_a,oSAT_crlg_c]  =  ...
		comps('/Volumes/matlab/matlab/eddy-wind/tracks/oSAT_lat_lon_tracks.mat',...
				'nrhp66_crlg_sample','n');		
				
%}				
			
save -append /Volumes/matlab/matlab/eddy-wind/norm_comps_16_weeks * 

				
				

