load new_north_south_comps r c

[north_rnfoi_a,north_rnfoi_c]=comps('north_tracks_16_weeks_6_cm', ...
                                    'nrfoi_sample');
[south_rnfoi_a,south_rnfoi_c]=comps('../south/south_tracks_16_weeks_6_cm', ...
                                    'nrfoi_sample');
[north_rnstr_a,north_rnstr_c]=comps('north_tracks_16_weeks_6_cm', ...
                                    'nrstr_sample');
[south_rnstr_a,south_rnstr_c]=comps('../south/south_tracks_16_weeks_6_cm', ...
                                    'nrstr_sample');
[north_rnspd_a,north_rnspd_c]=comps('north_tracks_16_weeks_6_cm', ...
                                    'nrspd_sample');
[south_rnspd_a,south_rnspd_c]=comps('../south/south_tracks_16_weeks_6_cm', ...
                                    'nrspd_sample');
%[north_rncrl_a,north_rncrl_c]=comps('north_tracks_16_weeks_6_cm', ...
%                                    'nrcrl_sample');
%[south_rncrl_a,south_rncrl_c]=comps('../south/south_tracks_16_weeks_6_cm', ...
%                                    'nrcrl_sample');          
%[north_rnstrcrl_a,north_rnstrcrl_c]=comps('north_tracks_16_weeks_6_cm', ...
%                                    'nrstrcrl_sample');
%[south_rnstrcrl_a,south_rnstrcrl_c]=comps('../south/south_tracks_16_weeks_6_cm', ...
%                                    'nrstrcrl_sample');                                           
                

save new_north_south_comps
                                    