clear all

curs = {'new_SP',...
    'AGR',...
    'HAW',...
    'EIO',...
    'CAR',...
    'AGU',...
    'new_EIO',...
    'new_SEA',...
    'SP'};



for mm=1:6
    
    load(['~/data/eddy/V6/',curs{mm},'_lat_lon_tracks_V6'])
    ii=find(track_jday>=2452466 & track_jday<=2455126 & age>=12);
    ext_x=ext_x(ii);
    ext_y=ext_y(ii);
    k=k(ii);
    id=id(ii);
    track_jday=track_jday(ii);
    cyc=cyc(ii);
    scale=scale(ii);
    
    
    eval(['[',curs{mm},'_wek_total_a,',curs{mm},'_wek_total_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
        char(39),'hp_total_wek_est2',char(39),',',char(39),...
        '~/data/QuickScat/ULTI_mat5/QSCAT_30_25km_',char(39),',',...
        char(39),'n',char(39),');'])
    
    eval(['[',curs{mm},'_wek_total_qscat_a,',curs{mm},'_wek_total_qscat_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
        char(39),'hp_total_wek_qscat2',char(39),',',char(39),...
        '~/data/QuickScat/ULTI_mat5/QSCAT_30_25km_',char(39),',',...
        char(39),'n',char(39),');'])
    
%     eval(['[',curs{mm},'_fixed_wek_sst_a,',curs{mm},'_fixed_wek_sst_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
%         char(39),'hp_wek_sst_week_fixed',char(39),',',char(39),...
%         '~/data/QuickScat/ULTI_mat4/QSCAT_30_25km_',char(39),',',...
%         char(39),'n',char(39),');'])
%     
%     eval(['[',curs{mm},'_crlg_a,',curs{mm},'_crlg_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
%         char(39),'hp66_crlg',char(39),',',char(39),...
%         '~/data/eddy/V5/mat/AVISO_25_W_',char(39),',',...
%         char(39),'n',char(39),');'])
%     
%     eval(['[',curs{mm},'_ssh_a,',curs{mm},'_ssh_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
%         char(39),'ssh',char(39),',',char(39),...
%         '~/data/eddy/V5/mat/AVISO_25_W_',char(39),',',...
%         char(39),'n',char(39),');'])
%     
%     eval(['[',curs{mm},'_sst_a,',curs{mm},'_sst_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
%         char(39),'hp66_sst',char(39),',',char(39),...
%         '~/data/ReynoldsSST/mat/OI_25_30_',char(39),',',...
%         char(39),'n',char(39),');'])
% %     
%     eval(['[',curs{mm},'_dtdn_a,',curs{mm},'_dtdn_c]=comps(ext_x,ext_y,cyc,k,id,track_jday,scale,'...
%         char(39),'norm_hp66_dtdn',char(39),',',char(39),...
%         '~/data/QuickScat/ULTI_mat4/QSCAT_30_25km_',char(39),',',...
%         char(39),'n',char(39),');'])
    
    save -append GAUBE_region_comps
end






